// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: File.proto
// Protobuf C++ Version: 6.33.4

#ifndef File_2eproto_2epb_2eh
#define File_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033004
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_File_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_File_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_File_2eproto;
}  // extern "C"
enum CmdType : int;
extern const uint32_t CmdType_internal_data_[];
class FileItem;
struct FileItemDefaultTypeInternal;
extern FileItemDefaultTypeInternal _FileItem_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FileItem_class_data_;
class FileRequest;
struct FileRequestDefaultTypeInternal;
extern FileRequestDefaultTypeInternal _FileRequest_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FileRequest_class_data_;
class FileResponse;
struct FileResponseDefaultTypeInternal;
extern FileResponseDefaultTypeInternal _FileResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull FileResponse_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::CmdType_internal_data_>
    internal::EnumTraitsImpl::value<::CmdType>;
}  // namespace protobuf
}  // namespace google

enum CmdType : int {
  UPLOAD_FILE = 0,
  DOWNLOAD_FILE = 1,
  DELETE_FILE = 2,
  LIST_FILE = 3,
  MKDIR = 4,
  RENAME_FILE = 5,
  UPLOAD_CHECK = 6,
  DOWNLOAD_CHECK = 7,
  CmdType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::min(),
  CmdType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      ::std::numeric_limits<::int32_t>::max(),
};

extern const uint32_t CmdType_internal_data_[];
inline constexpr CmdType CmdType_MIN =
    static_cast<CmdType>(0);
inline constexpr CmdType CmdType_MAX =
    static_cast<CmdType>(7);
inline bool CmdType_IsValid(int value) {
  return 0 <= value && value <= 7;
}
inline constexpr int CmdType_ARRAYSIZE = 7 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CmdType_descriptor();
template <typename T>
const ::std::string& CmdType_Name(T value) {
  static_assert(::std::is_same<T, CmdType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to CmdType_Name().");
  return CmdType_Name(static_cast<CmdType>(value));
}
template <>
inline const ::std::string& CmdType_Name(CmdType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<CmdType_descriptor, 0, 7>(
      static_cast<int>(value));
}
inline bool CmdType_Parse(
    ::absl::string_view name, CmdType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<CmdType>(CmdType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class FileRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:FileRequest) */ {
 public:
  inline FileRequest() : FileRequest(nullptr) {}
  ~FileRequest() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FileRequest* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FileRequest));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FileRequest(::google::protobuf::internal::ConstantInitialized);

  inline FileRequest(const FileRequest& from) : FileRequest(nullptr, from) {}
  inline FileRequest(FileRequest&& from) noexcept
      : FileRequest(nullptr, ::std::move(from)) {}
  inline FileRequest& operator=(const FileRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileRequest& operator=(FileRequest&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileRequest& default_instance() {
    return *reinterpret_cast<const FileRequest*>(
        &_FileRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(FileRequest& a, FileRequest& b) { a.Swap(&b); }
  inline void Swap(FileRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileRequest* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileRequest* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FileRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FileRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FileRequest& from) { FileRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FileRequest* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "FileRequest"; }

  explicit FileRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FileRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FileRequest& from);
  FileRequest(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FileRequest&& from) noexcept
      : FileRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTokenFieldNumber = 2,
    kClientIDFieldNumber = 3,
    kFilenameFieldNumber = 5,
    kDataFieldNumber = 10,
    kMd5FieldNumber = 11,
    kIvFieldNumber = 12,
    kPathFieldNumber = 13,
    kChunkMd5FieldNumber = 14,
    kTypeFieldNumber = 1,
    kSeckeyIDFieldNumber = 4,
    kFilesizeFieldNumber = 6,
    kOffsetFieldNumber = 7,
    kEofFieldNumber = 8,
    kChunkSizeFieldNumber = 9,
  };
  // string token = 2;
  void clear_token() ;
  const ::std::string& token() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_token(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_token();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_token();
  void set_allocated_token(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_token() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_token(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_token();

  public:
  // string clientID = 3;
  void clear_clientid() ;
  const ::std::string& clientid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_clientid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_clientid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_clientid();
  void set_allocated_clientid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_clientid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_clientid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_clientid();

  public:
  // string filename = 5;
  void clear_filename() ;
  const ::std::string& filename() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_filename(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_filename();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_filename();
  void set_allocated_filename(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_filename() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_filename(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_filename();

  public:
  // bytes data = 10;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // bytes md5 = 11;
  void clear_md5() ;
  const ::std::string& md5() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_md5(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_md5();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_md5();
  void set_allocated_md5(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_md5() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_md5(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_md5();

  public:
  // bytes iv = 12;
  void clear_iv() ;
  const ::std::string& iv() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_iv(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_iv();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_iv();
  void set_allocated_iv(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_iv() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_iv(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_iv();

  public:
  // string path = 13;
  void clear_path() ;
  const ::std::string& path() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_path(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_path();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_path();
  void set_allocated_path(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_path() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_path(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_path();

  public:
  // bytes chunk_md5 = 14;
  void clear_chunk_md5() ;
  const ::std::string& chunk_md5() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_chunk_md5(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_chunk_md5();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_chunk_md5();
  void set_allocated_chunk_md5(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_chunk_md5() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_chunk_md5(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_chunk_md5();

  public:
  // .CmdType type = 1;
  void clear_type() ;
  ::CmdType type() const;
  void set_type(::CmdType value);

  private:
  ::CmdType _internal_type() const;
  void _internal_set_type(::CmdType value);

  public:
  // uint32 seckeyID = 4;
  void clear_seckeyid() ;
  ::uint32_t seckeyid() const;
  void set_seckeyid(::uint32_t value);

  private:
  ::uint32_t _internal_seckeyid() const;
  void _internal_set_seckeyid(::uint32_t value);

  public:
  // uint64 filesize = 6;
  void clear_filesize() ;
  ::uint64_t filesize() const;
  void set_filesize(::uint64_t value);

  private:
  ::uint64_t _internal_filesize() const;
  void _internal_set_filesize(::uint64_t value);

  public:
  // uint64 offset = 7;
  void clear_offset() ;
  ::uint64_t offset() const;
  void set_offset(::uint64_t value);

  private:
  ::uint64_t _internal_offset() const;
  void _internal_set_offset(::uint64_t value);

  public:
  // bool eof = 8;
  void clear_eof() ;
  bool eof() const;
  void set_eof(bool value);

  private:
  bool _internal_eof() const;
  void _internal_set_eof(bool value);

  public:
  // uint32 chunk_size = 9;
  void clear_chunk_size() ;
  ::uint32_t chunk_size() const;
  void set_chunk_size(::uint32_t value);

  private:
  ::uint32_t _internal_chunk_size() const;
  void _internal_set_chunk_size(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:FileRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 14,
                                   0, 53,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FileRequest& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr token_;
    ::google::protobuf::internal::ArenaStringPtr clientid_;
    ::google::protobuf::internal::ArenaStringPtr filename_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::google::protobuf::internal::ArenaStringPtr md5_;
    ::google::protobuf::internal::ArenaStringPtr iv_;
    ::google::protobuf::internal::ArenaStringPtr path_;
    ::google::protobuf::internal::ArenaStringPtr chunk_md5_;
    int type_;
    ::uint32_t seckeyid_;
    ::uint64_t filesize_;
    ::uint64_t offset_;
    bool eof_;
    ::uint32_t chunk_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_File_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FileRequest_class_data_;
// -------------------------------------------------------------------

class FileItem final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:FileItem) */ {
 public:
  inline FileItem() : FileItem(nullptr) {}
  ~FileItem() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FileItem* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FileItem));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FileItem(::google::protobuf::internal::ConstantInitialized);

  inline FileItem(const FileItem& from) : FileItem(nullptr, from) {}
  inline FileItem(FileItem&& from) noexcept
      : FileItem(nullptr, ::std::move(from)) {}
  inline FileItem& operator=(const FileItem& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileItem& operator=(FileItem&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileItem& default_instance() {
    return *reinterpret_cast<const FileItem*>(
        &_FileItem_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(FileItem& a, FileItem& b) { a.Swap(&b); }
  inline void Swap(FileItem* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileItem* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileItem* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FileItem>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FileItem& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FileItem& from) { FileItem::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FileItem* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "FileItem"; }

  explicit FileItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FileItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FileItem& from);
  FileItem(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FileItem&& from) noexcept
      : FileItem(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFilenameFieldNumber = 1,
    kModifyTimeFieldNumber = 4,
    kFilesizeFieldNumber = 2,
    kIsDirFieldNumber = 3,
  };
  // string filename = 1;
  void clear_filename() ;
  const ::std::string& filename() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_filename(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_filename();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_filename();
  void set_allocated_filename(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_filename() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_filename(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_filename();

  public:
  // string modifyTime = 4;
  void clear_modifytime() ;
  const ::std::string& modifytime() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_modifytime(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_modifytime();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_modifytime();
  void set_allocated_modifytime(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_modifytime() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_modifytime(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_modifytime();

  public:
  // uint64 filesize = 2;
  void clear_filesize() ;
  ::uint64_t filesize() const;
  void set_filesize(::uint64_t value);

  private:
  ::uint64_t _internal_filesize() const;
  void _internal_set_filesize(::uint64_t value);

  public:
  // bool isDir = 3;
  void clear_isdir() ;
  bool isdir() const;
  void set_isdir(bool value);

  private:
  bool _internal_isdir() const;
  void _internal_set_isdir(bool value);

  public:
  // @@protoc_insertion_point(class_scope:FileItem)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   0, 35,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FileItem& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr filename_;
    ::google::protobuf::internal::ArenaStringPtr modifytime_;
    ::uint64_t filesize_;
    bool isdir_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_File_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FileItem_class_data_;
// -------------------------------------------------------------------

class FileResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:FileResponse) */ {
 public:
  inline FileResponse() : FileResponse(nullptr) {}
  ~FileResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(FileResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(FileResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR FileResponse(::google::protobuf::internal::ConstantInitialized);

  inline FileResponse(const FileResponse& from) : FileResponse(nullptr, from) {}
  inline FileResponse(FileResponse&& from) noexcept
      : FileResponse(nullptr, ::std::move(from)) {}
  inline FileResponse& operator=(const FileResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileResponse& operator=(FileResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const FileResponse& default_instance() {
    return *reinterpret_cast<const FileResponse*>(
        &_FileResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(FileResponse& a, FileResponse& b) { a.Swap(&b); }
  inline void Swap(FileResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<FileResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const FileResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const FileResponse& from) { FileResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(FileResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "FileResponse"; }

  explicit FileResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  FileResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const FileResponse& from);
  FileResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, FileResponse&& from) noexcept
      : FileResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kFilesFieldNumber = 9,
    kMessageFieldNumber = 3,
    kClientIDFieldNumber = 4,
    kDataFieldNumber = 8,
    kMd5FieldNumber = 11,
    kTypeFieldNumber = 1,
    kStatusFieldNumber = 2,
    kEofFieldNumber = 6,
    kOffsetFieldNumber = 5,
    kFilesizeFieldNumber = 12,
    kChunkSizeFieldNumber = 10,
  };
  // repeated .FileItem files = 9;
  int files_size() const;
  private:
  int _internal_files_size() const;

  public:
  void clear_files() ;
  ::FileItem* PROTOBUF_NONNULL mutable_files(int index);
  ::google::protobuf::RepeatedPtrField<::FileItem>* PROTOBUF_NONNULL mutable_files();

  private:
  const ::google::protobuf::RepeatedPtrField<::FileItem>& _internal_files() const;
  ::google::protobuf::RepeatedPtrField<::FileItem>* PROTOBUF_NONNULL _internal_mutable_files();
  public:
  const ::FileItem& files(int index) const;
  ::FileItem* PROTOBUF_NONNULL add_files();
  const ::google::protobuf::RepeatedPtrField<::FileItem>& files() const;
  // string message = 3;
  void clear_message() ;
  const ::std::string& message() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_message(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_message();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_message();
  void set_allocated_message(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_message() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_message(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_message();

  public:
  // string clientID = 4;
  void clear_clientid() ;
  const ::std::string& clientid() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_clientid(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_clientid();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_clientid();
  void set_allocated_clientid(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_clientid() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_clientid(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_clientid();

  public:
  // bytes data = 8;
  void clear_data() ;
  const ::std::string& data() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_data(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_data();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_data();
  void set_allocated_data(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_data() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_data(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_data();

  public:
  // bytes md5 = 11;
  void clear_md5() ;
  const ::std::string& md5() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_md5(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_md5();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_md5();
  void set_allocated_md5(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_md5() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_md5(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_md5();

  public:
  // .CmdType type = 1;
  void clear_type() ;
  ::CmdType type() const;
  void set_type(::CmdType value);

  private:
  ::CmdType _internal_type() const;
  void _internal_set_type(::CmdType value);

  public:
  // bool status = 2;
  void clear_status() ;
  bool status() const;
  void set_status(bool value);

  private:
  bool _internal_status() const;
  void _internal_set_status(bool value);

  public:
  // bool eof = 6;
  void clear_eof() ;
  bool eof() const;
  void set_eof(bool value);

  private:
  bool _internal_eof() const;
  void _internal_set_eof(bool value);

  public:
  // uint64 offset = 5;
  void clear_offset() ;
  ::uint64_t offset() const;
  void set_offset(::uint64_t value);

  private:
  ::uint64_t _internal_offset() const;
  void _internal_set_offset(::uint64_t value);

  public:
  // uint64 filesize = 12;
  void clear_filesize() ;
  ::uint64_t filesize() const;
  void set_filesize(::uint64_t value);

  private:
  ::uint64_t _internal_filesize() const;
  void _internal_set_filesize(::uint64_t value);

  public:
  // uint32 chunk_size = 10;
  void clear_chunk_size() ;
  ::uint32_t chunk_size() const;
  void set_chunk_size(::uint32_t value);

  private:
  ::uint32_t _internal_chunk_size() const;
  void _internal_set_chunk_size(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:FileResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 11,
                                   1, 44,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const FileResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::FileItem > files_;
    ::google::protobuf::internal::ArenaStringPtr message_;
    ::google::protobuf::internal::ArenaStringPtr clientid_;
    ::google::protobuf::internal::ArenaStringPtr data_;
    ::google::protobuf::internal::ArenaStringPtr md5_;
    int type_;
    bool status_;
    bool eof_;
    ::uint64_t offset_;
    ::uint64_t filesize_;
    ::uint32_t chunk_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_File_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull FileResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// FileItem

// string filename = 1;
inline void FileItem::clear_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& FileItem::filename() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileItem.filename)
  return _internal_filename();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileItem::set_filename(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.filename_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FileItem.filename)
}
inline ::std::string* PROTOBUF_NONNULL FileItem::mutable_filename()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:FileItem.filename)
  return _s;
}
inline const ::std::string& FileItem::_internal_filename() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filename_.Get();
}
inline void FileItem::_internal_set_filename(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileItem::_internal_mutable_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.filename_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileItem::release_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FileItem.filename)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.filename_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.filename_.Set("", GetArena());
  }
  return released;
}
inline void FileItem::set_allocated_filename(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.filename_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.filename_.IsDefault()) {
    _impl_.filename_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FileItem.filename)
}

// uint64 filesize = 2;
inline void FileItem::clear_filesize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filesize_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint64_t FileItem::filesize() const {
  // @@protoc_insertion_point(field_get:FileItem.filesize)
  return _internal_filesize();
}
inline void FileItem::set_filesize(::uint64_t value) {
  _internal_set_filesize(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:FileItem.filesize)
}
inline ::uint64_t FileItem::_internal_filesize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filesize_;
}
inline void FileItem::_internal_set_filesize(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filesize_ = value;
}

// bool isDir = 3;
inline void FileItem::clear_isdir() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isdir_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline bool FileItem::isdir() const {
  // @@protoc_insertion_point(field_get:FileItem.isDir)
  return _internal_isdir();
}
inline void FileItem::set_isdir(bool value) {
  _internal_set_isdir(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:FileItem.isDir)
}
inline bool FileItem::_internal_isdir() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.isdir_;
}
inline void FileItem::_internal_set_isdir(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.isdir_ = value;
}

// string modifyTime = 4;
inline void FileItem::clear_modifytime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.modifytime_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& FileItem::modifytime() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileItem.modifyTime)
  return _internal_modifytime();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileItem::set_modifytime(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.modifytime_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FileItem.modifyTime)
}
inline ::std::string* PROTOBUF_NONNULL FileItem::mutable_modifytime()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_modifytime();
  // @@protoc_insertion_point(field_mutable:FileItem.modifyTime)
  return _s;
}
inline const ::std::string& FileItem::_internal_modifytime() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.modifytime_.Get();
}
inline void FileItem::_internal_set_modifytime(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.modifytime_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileItem::_internal_mutable_modifytime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.modifytime_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileItem::release_modifytime() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FileItem.modifyTime)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.modifytime_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.modifytime_.Set("", GetArena());
  }
  return released;
}
inline void FileItem::set_allocated_modifytime(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.modifytime_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.modifytime_.IsDefault()) {
    _impl_.modifytime_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FileItem.modifyTime)
}

// -------------------------------------------------------------------

// FileRequest

// .CmdType type = 1;
inline void FileRequest::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::CmdType FileRequest::type() const {
  // @@protoc_insertion_point(field_get:FileRequest.type)
  return _internal_type();
}
inline void FileRequest::set_type(::CmdType value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:FileRequest.type)
}
inline ::CmdType FileRequest::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::CmdType>(_impl_.type_);
}
inline void FileRequest::_internal_set_type(::CmdType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// string token = 2;
inline void FileRequest::clear_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.token_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& FileRequest::token() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileRequest.token)
  return _internal_token();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileRequest::set_token(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.token_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FileRequest.token)
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::mutable_token()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_token();
  // @@protoc_insertion_point(field_mutable:FileRequest.token)
  return _s;
}
inline const ::std::string& FileRequest::_internal_token() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.token_.Get();
}
inline void FileRequest::_internal_set_token(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.token_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::_internal_mutable_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.token_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileRequest::release_token() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FileRequest.token)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.token_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.token_.Set("", GetArena());
  }
  return released;
}
inline void FileRequest::set_allocated_token(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.token_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.token_.IsDefault()) {
    _impl_.token_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FileRequest.token)
}

// string clientID = 3;
inline void FileRequest::clear_clientid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& FileRequest::clientid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileRequest.clientID)
  return _internal_clientid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileRequest::set_clientid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.clientid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FileRequest.clientID)
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::mutable_clientid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_clientid();
  // @@protoc_insertion_point(field_mutable:FileRequest.clientID)
  return _s;
}
inline const ::std::string& FileRequest::_internal_clientid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clientid_.Get();
}
inline void FileRequest::_internal_set_clientid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::_internal_mutable_clientid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.clientid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileRequest::release_clientid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FileRequest.clientID)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.clientid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.clientid_.Set("", GetArena());
  }
  return released;
}
inline void FileRequest::set_allocated_clientid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.clientid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.clientid_.IsDefault()) {
    _impl_.clientid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FileRequest.clientID)
}

// uint32 seckeyID = 4;
inline void FileRequest::clear_seckeyid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seckeyid_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::uint32_t FileRequest::seckeyid() const {
  // @@protoc_insertion_point(field_get:FileRequest.seckeyID)
  return _internal_seckeyid();
}
inline void FileRequest::set_seckeyid(::uint32_t value) {
  _internal_set_seckeyid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:FileRequest.seckeyID)
}
inline ::uint32_t FileRequest::_internal_seckeyid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.seckeyid_;
}
inline void FileRequest::_internal_set_seckeyid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seckeyid_ = value;
}

// string filename = 5;
inline void FileRequest::clear_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& FileRequest::filename() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileRequest.filename)
  return _internal_filename();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileRequest::set_filename(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.filename_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FileRequest.filename)
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::mutable_filename()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:FileRequest.filename)
  return _s;
}
inline const ::std::string& FileRequest::_internal_filename() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filename_.Get();
}
inline void FileRequest::_internal_set_filename(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filename_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::_internal_mutable_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.filename_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileRequest::release_filename() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FileRequest.filename)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.filename_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.filename_.Set("", GetArena());
  }
  return released;
}
inline void FileRequest::set_allocated_filename(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.filename_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.filename_.IsDefault()) {
    _impl_.filename_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FileRequest.filename)
}

// uint64 filesize = 6;
inline void FileRequest::clear_filesize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filesize_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000400U);
}
inline ::uint64_t FileRequest::filesize() const {
  // @@protoc_insertion_point(field_get:FileRequest.filesize)
  return _internal_filesize();
}
inline void FileRequest::set_filesize(::uint64_t value) {
  _internal_set_filesize(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_set:FileRequest.filesize)
}
inline ::uint64_t FileRequest::_internal_filesize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filesize_;
}
inline void FileRequest::_internal_set_filesize(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filesize_ = value;
}

// uint64 offset = 7;
inline void FileRequest::clear_offset() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.offset_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000800U);
}
inline ::uint64_t FileRequest::offset() const {
  // @@protoc_insertion_point(field_get:FileRequest.offset)
  return _internal_offset();
}
inline void FileRequest::set_offset(::uint64_t value) {
  _internal_set_offset(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000800U);
  // @@protoc_insertion_point(field_set:FileRequest.offset)
}
inline ::uint64_t FileRequest::_internal_offset() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.offset_;
}
inline void FileRequest::_internal_set_offset(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.offset_ = value;
}

// bool eof = 8;
inline void FileRequest::clear_eof() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eof_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00001000U);
}
inline bool FileRequest::eof() const {
  // @@protoc_insertion_point(field_get:FileRequest.eof)
  return _internal_eof();
}
inline void FileRequest::set_eof(bool value) {
  _internal_set_eof(value);
  SetHasBit(_impl_._has_bits_[0], 0x00001000U);
  // @@protoc_insertion_point(field_set:FileRequest.eof)
}
inline bool FileRequest::_internal_eof() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.eof_;
}
inline void FileRequest::_internal_set_eof(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eof_ = value;
}

// uint32 chunk_size = 9;
inline void FileRequest::clear_chunk_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_size_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00002000U);
}
inline ::uint32_t FileRequest::chunk_size() const {
  // @@protoc_insertion_point(field_get:FileRequest.chunk_size)
  return _internal_chunk_size();
}
inline void FileRequest::set_chunk_size(::uint32_t value) {
  _internal_set_chunk_size(value);
  SetHasBit(_impl_._has_bits_[0], 0x00002000U);
  // @@protoc_insertion_point(field_set:FileRequest.chunk_size)
}
inline ::uint32_t FileRequest::_internal_chunk_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.chunk_size_;
}
inline void FileRequest::_internal_set_chunk_size(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_size_ = value;
}

// bytes data = 10;
inline void FileRequest::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& FileRequest::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileRequest.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileRequest::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FileRequest.data)
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:FileRequest.data)
  return _s;
}
inline const ::std::string& FileRequest::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void FileRequest::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileRequest::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FileRequest.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void FileRequest::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FileRequest.data)
}

// bytes md5 = 11;
inline void FileRequest::clear_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.md5_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& FileRequest::md5() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileRequest.md5)
  return _internal_md5();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileRequest::set_md5(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.md5_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FileRequest.md5)
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::mutable_md5()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_md5();
  // @@protoc_insertion_point(field_mutable:FileRequest.md5)
  return _s;
}
inline const ::std::string& FileRequest::_internal_md5() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.md5_.Get();
}
inline void FileRequest::_internal_set_md5(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.md5_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::_internal_mutable_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.md5_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileRequest::release_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FileRequest.md5)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.md5_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.md5_.Set("", GetArena());
  }
  return released;
}
inline void FileRequest::set_allocated_md5(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.md5_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.md5_.IsDefault()) {
    _impl_.md5_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FileRequest.md5)
}

// bytes iv = 12;
inline void FileRequest::clear_iv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iv_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline const ::std::string& FileRequest::iv() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileRequest.iv)
  return _internal_iv();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileRequest::set_iv(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  _impl_.iv_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FileRequest.iv)
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::mutable_iv()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  ::std::string* _s = _internal_mutable_iv();
  // @@protoc_insertion_point(field_mutable:FileRequest.iv)
  return _s;
}
inline const ::std::string& FileRequest::_internal_iv() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.iv_.Get();
}
inline void FileRequest::_internal_set_iv(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.iv_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::_internal_mutable_iv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.iv_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileRequest::release_iv() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FileRequest.iv)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000020U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  auto* released = _impl_.iv_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.iv_.Set("", GetArena());
  }
  return released;
}
inline void FileRequest::set_allocated_iv(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
  }
  _impl_.iv_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.iv_.IsDefault()) {
    _impl_.iv_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FileRequest.iv)
}

// string path = 13;
inline void FileRequest::clear_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline const ::std::string& FileRequest::path() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileRequest.path)
  return _internal_path();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileRequest::set_path(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  _impl_.path_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FileRequest.path)
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::mutable_path()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  ::std::string* _s = _internal_mutable_path();
  // @@protoc_insertion_point(field_mutable:FileRequest.path)
  return _s;
}
inline const ::std::string& FileRequest::_internal_path() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.path_.Get();
}
inline void FileRequest::_internal_set_path(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.path_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::_internal_mutable_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.path_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileRequest::release_path() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FileRequest.path)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000040U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  auto* released = _impl_.path_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.path_.Set("", GetArena());
  }
  return released;
}
inline void FileRequest::set_allocated_path(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000040U);
  }
  _impl_.path_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.path_.IsDefault()) {
    _impl_.path_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FileRequest.path)
}

// bytes chunk_md5 = 14;
inline void FileRequest::clear_chunk_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_md5_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline const ::std::string& FileRequest::chunk_md5() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileRequest.chunk_md5)
  return _internal_chunk_md5();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileRequest::set_chunk_md5(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  _impl_.chunk_md5_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FileRequest.chunk_md5)
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::mutable_chunk_md5()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  ::std::string* _s = _internal_mutable_chunk_md5();
  // @@protoc_insertion_point(field_mutable:FileRequest.chunk_md5)
  return _s;
}
inline const ::std::string& FileRequest::_internal_chunk_md5() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.chunk_md5_.Get();
}
inline void FileRequest::_internal_set_chunk_md5(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_md5_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileRequest::_internal_mutable_chunk_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.chunk_md5_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileRequest::release_chunk_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FileRequest.chunk_md5)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000080U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
  auto* released = _impl_.chunk_md5_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.chunk_md5_.Set("", GetArena());
  }
  return released;
}
inline void FileRequest::set_allocated_chunk_md5(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000080U);
  }
  _impl_.chunk_md5_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.chunk_md5_.IsDefault()) {
    _impl_.chunk_md5_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FileRequest.chunk_md5)
}

// -------------------------------------------------------------------

// FileResponse

// .CmdType type = 1;
inline void FileResponse::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::CmdType FileResponse::type() const {
  // @@protoc_insertion_point(field_get:FileResponse.type)
  return _internal_type();
}
inline void FileResponse::set_type(::CmdType value) {
  _internal_set_type(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:FileResponse.type)
}
inline ::CmdType FileResponse::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::CmdType>(_impl_.type_);
}
inline void FileResponse::_internal_set_type(::CmdType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// bool status = 2;
inline void FileResponse::clear_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline bool FileResponse::status() const {
  // @@protoc_insertion_point(field_get:FileResponse.status)
  return _internal_status();
}
inline void FileResponse::set_status(bool value) {
  _internal_set_status(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:FileResponse.status)
}
inline bool FileResponse::_internal_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.status_;
}
inline void FileResponse::_internal_set_status(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.status_ = value;
}

// string message = 3;
inline void FileResponse::clear_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& FileResponse::message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileResponse.message)
  return _internal_message();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileResponse::set_message(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FileResponse.message)
}
inline ::std::string* PROTOBUF_NONNULL FileResponse::mutable_message()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:FileResponse.message)
  return _s;
}
inline const ::std::string& FileResponse::_internal_message() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.message_.Get();
}
inline void FileResponse::_internal_set_message(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.message_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileResponse::_internal_mutable_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.message_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileResponse::release_message() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FileResponse.message)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.message_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.message_.Set("", GetArena());
  }
  return released;
}
inline void FileResponse::set_allocated_message(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.message_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FileResponse.message)
}

// string clientID = 4;
inline void FileResponse::clear_clientid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientid_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& FileResponse::clientid() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileResponse.clientID)
  return _internal_clientid();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileResponse::set_clientid(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.clientid_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FileResponse.clientID)
}
inline ::std::string* PROTOBUF_NONNULL FileResponse::mutable_clientid()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_clientid();
  // @@protoc_insertion_point(field_mutable:FileResponse.clientID)
  return _s;
}
inline const ::std::string& FileResponse::_internal_clientid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.clientid_.Get();
}
inline void FileResponse::_internal_set_clientid(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.clientid_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileResponse::_internal_mutable_clientid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.clientid_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileResponse::release_clientid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FileResponse.clientID)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.clientid_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.clientid_.Set("", GetArena());
  }
  return released;
}
inline void FileResponse::set_allocated_clientid(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.clientid_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.clientid_.IsDefault()) {
    _impl_.clientid_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FileResponse.clientID)
}

// uint64 offset = 5;
inline void FileResponse::clear_offset() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.offset_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::uint64_t FileResponse::offset() const {
  // @@protoc_insertion_point(field_get:FileResponse.offset)
  return _internal_offset();
}
inline void FileResponse::set_offset(::uint64_t value) {
  _internal_set_offset(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:FileResponse.offset)
}
inline ::uint64_t FileResponse::_internal_offset() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.offset_;
}
inline void FileResponse::_internal_set_offset(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.offset_ = value;
}

// bool eof = 6;
inline void FileResponse::clear_eof() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eof_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline bool FileResponse::eof() const {
  // @@protoc_insertion_point(field_get:FileResponse.eof)
  return _internal_eof();
}
inline void FileResponse::set_eof(bool value) {
  _internal_set_eof(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:FileResponse.eof)
}
inline bool FileResponse::_internal_eof() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.eof_;
}
inline void FileResponse::_internal_set_eof(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eof_ = value;
}

// bytes data = 8;
inline void FileResponse::clear_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& FileResponse::data() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileResponse.data)
  return _internal_data();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileResponse::set_data(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.data_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FileResponse.data)
}
inline ::std::string* PROTOBUF_NONNULL FileResponse::mutable_data()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_data();
  // @@protoc_insertion_point(field_mutable:FileResponse.data)
  return _s;
}
inline const ::std::string& FileResponse::_internal_data() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.data_.Get();
}
inline void FileResponse::_internal_set_data(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.data_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileResponse::_internal_mutable_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.data_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileResponse::release_data() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FileResponse.data)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.data_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.data_.Set("", GetArena());
  }
  return released;
}
inline void FileResponse::set_allocated_data(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.data_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.data_.IsDefault()) {
    _impl_.data_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FileResponse.data)
}

// repeated .FileItem files = 9;
inline int FileResponse::_internal_files_size() const {
  return _internal_files().size();
}
inline int FileResponse::files_size() const {
  return _internal_files_size();
}
inline void FileResponse::clear_files() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.files_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::FileItem* PROTOBUF_NONNULL FileResponse::mutable_files(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:FileResponse.files)
  return _internal_mutable_files()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::FileItem>* PROTOBUF_NONNULL FileResponse::mutable_files()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:FileResponse.files)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_files();
}
inline const ::FileItem& FileResponse::files(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileResponse.files)
  return _internal_files().Get(index);
}
inline ::FileItem* PROTOBUF_NONNULL FileResponse::add_files()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::FileItem* _add =
      _internal_mutable_files()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:FileResponse.files)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::FileItem>& FileResponse::files() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:FileResponse.files)
  return _internal_files();
}
inline const ::google::protobuf::RepeatedPtrField<::FileItem>&
FileResponse::_internal_files() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.files_;
}
inline ::google::protobuf::RepeatedPtrField<::FileItem>* PROTOBUF_NONNULL
FileResponse::_internal_mutable_files() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.files_;
}

// uint32 chunk_size = 10;
inline void FileResponse::clear_chunk_size() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_size_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000400U);
}
inline ::uint32_t FileResponse::chunk_size() const {
  // @@protoc_insertion_point(field_get:FileResponse.chunk_size)
  return _internal_chunk_size();
}
inline void FileResponse::set_chunk_size(::uint32_t value) {
  _internal_set_chunk_size(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000400U);
  // @@protoc_insertion_point(field_set:FileResponse.chunk_size)
}
inline ::uint32_t FileResponse::_internal_chunk_size() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.chunk_size_;
}
inline void FileResponse::_internal_set_chunk_size(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.chunk_size_ = value;
}

// bytes md5 = 11;
inline void FileResponse::clear_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.md5_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& FileResponse::md5() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:FileResponse.md5)
  return _internal_md5();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void FileResponse::set_md5(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.md5_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:FileResponse.md5)
}
inline ::std::string* PROTOBUF_NONNULL FileResponse::mutable_md5()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_md5();
  // @@protoc_insertion_point(field_mutable:FileResponse.md5)
  return _s;
}
inline const ::std::string& FileResponse::_internal_md5() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.md5_.Get();
}
inline void FileResponse::_internal_set_md5(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.md5_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL FileResponse::_internal_mutable_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.md5_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE FileResponse::release_md5() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:FileResponse.md5)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.md5_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.md5_.Set("", GetArena());
  }
  return released;
}
inline void FileResponse::set_allocated_md5(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.md5_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.md5_.IsDefault()) {
    _impl_.md5_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:FileResponse.md5)
}

// uint64 filesize = 12;
inline void FileResponse::clear_filesize() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filesize_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000200U);
}
inline ::uint64_t FileResponse::filesize() const {
  // @@protoc_insertion_point(field_get:FileResponse.filesize)
  return _internal_filesize();
}
inline void FileResponse::set_filesize(::uint64_t value) {
  _internal_set_filesize(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000200U);
  // @@protoc_insertion_point(field_set:FileResponse.filesize)
}
inline ::uint64_t FileResponse::_internal_filesize() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.filesize_;
}
inline void FileResponse::_internal_set_filesize(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.filesize_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::CmdType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::CmdType>() {
  return ::CmdType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // File_2eproto_2epb_2eh
