// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: File.proto
// Protobuf C++ Version: 6.33.4

#include "File.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr FileRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        block_hashs_{},
        block_size_{},
        _block_size_cached_byte_size_{0},
        token_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        clientid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        md5_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        iv_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        path_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        chunk_md5_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        block_hash_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_{static_cast< ::CmdType >(0)},
        seckeyid_{0u},
        filesize_{::uint64_t{0u}},
        offset_{::uint64_t{0u}},
        eof_{false},
        chunk_size_{0u},
        upload_id_{::uint64_t{0u}},
        chunk_index_{::uint64_t{0u}},
        version_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR FileRequest::FileRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(FileRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileRequestDefaultTypeInternal() {}
  union {
    FileRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileRequestDefaultTypeInternal _FileRequest_default_instance_;

inline constexpr FileItem::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        filename_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        modifytime_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        filesize_{::uint64_t{0u}},
        isdir_{false} {}

template <typename>
PROTOBUF_CONSTEXPR FileItem::FileItem(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(FileItem_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileItemDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileItemDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileItemDefaultTypeInternal() {}
  union {
    FileItem _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileItemDefaultTypeInternal _FileItem_default_instance_;

inline constexpr FileResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        files_{},
        finished_chunks_{},
        _finished_chunks_cached_byte_size_{0},
        missing_hashes_{},
        block_offsets_{},
        _block_offsets_cached_byte_size_{0},
        message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        clientid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        data_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        md5_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        type_{static_cast< ::CmdType >(0)},
        status_{false},
        eof_{false},
        offset_{::uint64_t{0u}},
        filesize_{::uint64_t{0u}},
        upload_id_{::uint64_t{0u}},
        chunk_size_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR FileResponse::FileResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(FileResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct FileResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR FileResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~FileResponseDefaultTypeInternal() {}
  union {
    FileResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 FileResponseDefaultTypeInternal _FileResponse_default_instance_;
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_File_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_File_2eproto = nullptr;
const ::uint32_t
    TableStruct_File_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::FileItem, _impl_._has_bits_),
        7, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::FileItem, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::FileItem, _impl_.filesize_),
        PROTOBUF_FIELD_OFFSET(::FileItem, _impl_.isdir_),
        PROTOBUF_FIELD_OFFSET(::FileItem, _impl_.modifytime_),
        0,
        2,
        3,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_._has_bits_),
        23, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.token_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.clientid_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.seckeyid_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.filename_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.filesize_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.offset_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.eof_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.chunk_size_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.md5_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.iv_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.path_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.chunk_md5_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.upload_id_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.chunk_index_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.version_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.block_hash_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.block_hashs_),
        PROTOBUF_FIELD_OFFSET(::FileRequest, _impl_.block_size_),
        11,
        2,
        3,
        12,
        4,
        13,
        14,
        15,
        16,
        5,
        6,
        7,
        8,
        9,
        17,
        18,
        19,
        10,
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_._has_bits_),
        18, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.type_),
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.status_),
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.message_),
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.clientid_),
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.offset_),
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.eof_),
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.data_),
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.files_),
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.chunk_size_),
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.md5_),
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.filesize_),
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.upload_id_),
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.finished_chunks_),
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.missing_hashes_),
        PROTOBUF_FIELD_OFFSET(::FileResponse, _impl_.block_offsets_),
        8,
        9,
        4,
        5,
        11,
        10,
        6,
        0,
        14,
        7,
        12,
        13,
        1,
        2,
        3,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::FileItem)},
        {11, sizeof(::FileRequest)},
        {54, sizeof(::FileResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_FileItem_default_instance_._instance,
    &::_FileRequest_default_instance_._instance,
    &::_FileResponse_default_instance_._instance,
};
const char descriptor_table_protodef_File_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\nFile.proto\"Q\n\010FileItem\022\020\n\010filename\030\001 \001"
    "(\t\022\020\n\010filesize\030\002 \001(\004\022\r\n\005isDir\030\003 \001(\010\022\022\n\nm"
    "odifyTime\030\004 \001(\t\"\353\002\n\013FileRequest\022\026\n\004type\030"
    "\001 \001(\0162\010.CmdType\022\r\n\005token\030\002 \001(\t\022\020\n\010client"
    "ID\030\003 \001(\t\022\020\n\010seckeyID\030\004 \001(\r\022\020\n\010filename\030\005"
    " \001(\t\022\020\n\010filesize\030\006 \001(\004\022\016\n\006offset\030\007 \001(\004\022\013"
    "\n\003eof\030\010 \001(\010\022\022\n\nchunk_size\030\t \001(\r\022\014\n\004data\030"
    "\n \001(\014\022\013\n\003md5\030\013 \001(\014\022\n\n\002iv\030\014 \001(\014\022\014\n\004path\030\r"
    " \001(\t\022\021\n\tchunk_md5\030\016 \001(\014\022\021\n\tupload_id\030\017 \001"
    "(\004\022\023\n\013chunk_index\030\020 \001(\004\022\017\n\007version\030\021 \001(\004"
    "\022\022\n\nblock_hash\030\022 \001(\014\022\023\n\013block_hashs\030\023 \003("
    "\014\022\022\n\nblock_size\030\024 \003(\r\"\254\002\n\014FileResponse\022\026"
    "\n\004type\030\001 \001(\0162\010.CmdType\022\016\n\006status\030\002 \001(\010\022\017"
    "\n\007message\030\003 \001(\t\022\020\n\010clientID\030\004 \001(\t\022\016\n\006off"
    "set\030\005 \001(\004\022\013\n\003eof\030\006 \001(\010\022\014\n\004data\030\010 \001(\014\022\030\n\005"
    "files\030\t \003(\0132\t.FileItem\022\022\n\nchunk_size\030\n \001"
    "(\r\022\013\n\003md5\030\013 \001(\014\022\020\n\010filesize\030\014 \001(\004\022\021\n\tupl"
    "oad_id\030\r \001(\004\022\027\n\017finished_chunks\030\016 \003(\r\022\026\n"
    "\016missing_hashes\030\017 \003(\014\022\025\n\rblock_offsets\030\020"
    " \003(\004*\301\001\n\007CmdType\022\017\n\013UPLOAD_FILE\020\000\022\021\n\rDOW"
    "NLOAD_FILE\020\001\022\017\n\013DELETE_FILE\020\002\022\r\n\tLIST_FI"
    "LE\020\003\022\t\n\005MKDIR\020\004\022\017\n\013RENAME_FILE\020\005\022\020\n\014UPLO"
    "AD_CHECK\020\006\022\022\n\016DOWNLOAD_CHECK\020\007\022\016\n\nSYNC_C"
    "HECK\020\010\022\017\n\013SYNC_UPLOAD\020\t\022\017\n\013SYNC_COMMIT\020\n"
    "b\006proto3"
};
static ::absl::once_flag descriptor_table_File_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_File_2eproto = {
    false,
    false,
    968,
    descriptor_table_protodef_File_2eproto,
    "File.proto",
    &descriptor_table_File_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_File_2eproto::offsets,
    file_level_enum_descriptors_File_2eproto,
    file_level_service_descriptors_File_2eproto,
};
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL CmdType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_File_2eproto);
  return file_level_enum_descriptors_File_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t CmdType_internal_data_[] = {
    720896u, 0u, };
// ===================================================================

class FileItem::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<FileItem>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FileItem, _impl_._has_bits_);
};

FileItem::FileItem(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FileItem_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FileItem)
}
PROTOBUF_NDEBUG_INLINE FileItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::FileItem& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        filename_(arena, from.filename_),
        modifytime_(arena, from.modifytime_) {}

FileItem::FileItem(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const FileItem& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FileItem_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FileItem* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, filesize_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, filesize_),
           offsetof(Impl_, isdir_) -
               offsetof(Impl_, filesize_) +
               sizeof(Impl_::isdir_));

  // @@protoc_insertion_point(copy_constructor:FileItem)
}
PROTOBUF_NDEBUG_INLINE FileItem::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        filename_(arena),
        modifytime_(arena) {}

inline void FileItem::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, filesize_),
           0,
           offsetof(Impl_, isdir_) -
               offsetof(Impl_, filesize_) +
               sizeof(Impl_::isdir_));
}
FileItem::~FileItem() {
  // @@protoc_insertion_point(destructor:FileItem)
  SharedDtor(*this);
}
inline void FileItem::SharedDtor(MessageLite& self) {
  FileItem& this_ = static_cast<FileItem&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.filename_.Destroy();
  this_._impl_.modifytime_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL FileItem::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FileItem(arena);
}
constexpr auto FileItem::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(FileItem),
                                            alignof(FileItem));
}
constexpr auto FileItem::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_FileItem_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &FileItem::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<FileItem>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FileItem::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<FileItem>(), &FileItem::ByteSizeLong,
              &FileItem::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FileItem, _impl_._cached_size_),
          false,
      },
      &FileItem::kDescriptorMethods,
      &descriptor_table_File_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull FileItem_class_data_ =
        FileItem::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FileItem::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FileItem_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(FileItem_class_data_.tc_table);
  return FileItem_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 4, 0, 35, 2>
FileItem::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FileItem, _impl_._has_bits_),
    0, // no _extensions_
    4, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967280,  // skipmap
    offsetof(decltype(_table_), field_entries),
    4,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    FileItem_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FileItem>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // string modifyTime = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 1, 0,
      PROTOBUF_FIELD_OFFSET(FileItem, _impl_.modifytime_)}},
    // string filename = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(FileItem, _impl_.filename_)}},
    // uint64 filesize = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileItem, _impl_.filesize_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(FileItem, _impl_.filesize_)}},
    // bool isDir = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FileItem, _impl_.isdir_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(FileItem, _impl_.isdir_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string filename = 1;
    {PROTOBUF_FIELD_OFFSET(FileItem, _impl_.filename_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint64 filesize = 2;
    {PROTOBUF_FIELD_OFFSET(FileItem, _impl_.filesize_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // bool isDir = 3;
    {PROTOBUF_FIELD_OFFSET(FileItem, _impl_.isdir_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string modifyTime = 4;
    {PROTOBUF_FIELD_OFFSET(FileItem, _impl_.modifytime_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\10\10\0\0\12\0\0\0"
    "FileItem"
    "filename"
    "modifyTime"
  }},
};
PROTOBUF_NOINLINE void FileItem::Clear() {
// @@protoc_insertion_point(message_clear_start:FileItem)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x00000003U)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.filename_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.modifytime_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000000cU)) {
    ::memset(&_impl_.filesize_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.isdir_) -
        reinterpret_cast<char*>(&_impl_.filesize_)) + sizeof(_impl_.isdir_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL FileItem::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const FileItem& this_ = static_cast<const FileItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL FileItem::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const FileItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:FileItem)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string filename = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    if (!this_._internal_filename().empty()) {
      const ::std::string& _s = this_._internal_filename();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FileItem.filename");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // uint64 filesize = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (this_._internal_filesize() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          2, this_._internal_filesize(), target);
    }
  }

  // bool isDir = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (this_._internal_isdir() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          3, this_._internal_isdir(), target);
    }
  }

  // string modifyTime = 4;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    if (!this_._internal_modifytime().empty()) {
      const ::std::string& _s = this_._internal_modifytime();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FileItem.modifyTime");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FileItem)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FileItem::ByteSizeLong(const MessageLite& base) {
  const FileItem& this_ = static_cast<const FileItem&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FileItem::ByteSizeLong() const {
  const FileItem& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:FileItem)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    // string filename = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!this_._internal_filename().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_filename());
      }
    }
    // string modifyTime = 4;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!this_._internal_modifytime().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_modifytime());
      }
    }
    // uint64 filesize = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (this_._internal_filesize() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_filesize());
      }
    }
    // bool isDir = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (this_._internal_isdir() != 0) {
        total_size += 2;
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void FileItem::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<FileItem*>(&to_msg);
  auto& from = static_cast<const FileItem&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:FileItem)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      if (!from._internal_filename().empty()) {
        _this->_internal_set_filename(from._internal_filename());
      } else {
        if (_this->_impl_.filename_.IsDefault()) {
          _this->_internal_set_filename("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      if (!from._internal_modifytime().empty()) {
        _this->_internal_set_modifytime(from._internal_modifytime());
      } else {
        if (_this->_impl_.modifytime_.IsDefault()) {
          _this->_internal_set_modifytime("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (from._internal_filesize() != 0) {
        _this->_impl_.filesize_ = from._impl_.filesize_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (from._internal_isdir() != 0) {
        _this->_impl_.isdir_ = from._impl_.isdir_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void FileItem::CopyFrom(const FileItem& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:FileItem)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FileItem::InternalSwap(FileItem* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.modifytime_, &other->_impl_.modifytime_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileItem, _impl_.isdir_)
      + sizeof(FileItem::_impl_.isdir_)
      - PROTOBUF_FIELD_OFFSET(FileItem, _impl_.filesize_)>(
          reinterpret_cast<char*>(&_impl_.filesize_),
          reinterpret_cast<char*>(&other->_impl_.filesize_));
}

::google::protobuf::Metadata FileItem::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FileRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<FileRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FileRequest, _impl_._has_bits_);
};

FileRequest::FileRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FileRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FileRequest)
}
PROTOBUF_NDEBUG_INLINE FileRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::FileRequest& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        block_hashs_{visibility, arena, from.block_hashs_},
        block_size_{visibility, arena, from.block_size_},
        _block_size_cached_byte_size_{0},
        token_(arena, from.token_),
        clientid_(arena, from.clientid_),
        filename_(arena, from.filename_),
        data_(arena, from.data_),
        md5_(arena, from.md5_),
        iv_(arena, from.iv_),
        path_(arena, from.path_),
        chunk_md5_(arena, from.chunk_md5_),
        block_hash_(arena, from.block_hash_) {}

FileRequest::FileRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const FileRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FileRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FileRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, type_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, type_),
           offsetof(Impl_, version_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::version_));

  // @@protoc_insertion_point(copy_constructor:FileRequest)
}
PROTOBUF_NDEBUG_INLINE FileRequest::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        block_hashs_{visibility, arena},
        block_size_{visibility, arena},
        _block_size_cached_byte_size_{0},
        token_(arena),
        clientid_(arena),
        filename_(arena),
        data_(arena),
        md5_(arena),
        iv_(arena),
        path_(arena),
        chunk_md5_(arena),
        block_hash_(arena) {}

inline void FileRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, type_),
           0,
           offsetof(Impl_, version_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::version_));
}
FileRequest::~FileRequest() {
  // @@protoc_insertion_point(destructor:FileRequest)
  SharedDtor(*this);
}
inline void FileRequest::SharedDtor(MessageLite& self) {
  FileRequest& this_ = static_cast<FileRequest&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.token_.Destroy();
  this_._impl_.clientid_.Destroy();
  this_._impl_.filename_.Destroy();
  this_._impl_.data_.Destroy();
  this_._impl_.md5_.Destroy();
  this_._impl_.iv_.Destroy();
  this_._impl_.path_.Destroy();
  this_._impl_.chunk_md5_.Destroy();
  this_._impl_.block_hash_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL FileRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FileRequest(arena);
}
constexpr auto FileRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.block_hashs_) +
          decltype(FileRequest::_impl_.block_hashs_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.block_size_) +
          decltype(FileRequest::_impl_.block_size_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(FileRequest), alignof(FileRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&FileRequest::PlacementNew_,
                                 sizeof(FileRequest),
                                 alignof(FileRequest));
  }
}
constexpr auto FileRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_FileRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &FileRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<FileRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FileRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<FileRequest>(), &FileRequest::ByteSizeLong,
              &FileRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FileRequest, _impl_._cached_size_),
          false,
      },
      &FileRequest::kDescriptorMethods,
      &descriptor_table_File_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull FileRequest_class_data_ =
        FileRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FileRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FileRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(FileRequest_class_data_.tc_table);
  return FileRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<5, 20, 0, 61, 2>
FileRequest::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FileRequest, _impl_._has_bits_),
    0, // no _extensions_
    20, 248,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4293918720,  // skipmap
    offsetof(decltype(_table_), field_entries),
    20,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    FileRequest_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FileRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .CmdType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileRequest, _impl_.type_), 11>(),
     {8, 11, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.type_)}},
    // string token = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 2, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.token_)}},
    // string clientID = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 3, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.clientid_)}},
    // uint32 seckeyID = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileRequest, _impl_.seckeyid_), 12>(),
     {32, 12, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.seckeyid_)}},
    // string filename = 5;
    {::_pbi::TcParser::FastUS1,
     {42, 4, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.filename_)}},
    // uint64 filesize = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileRequest, _impl_.filesize_), 13>(),
     {48, 13, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.filesize_)}},
    // uint64 offset = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileRequest, _impl_.offset_), 14>(),
     {56, 14, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.offset_)}},
    // bool eof = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FileRequest, _impl_.eof_), 15>(),
     {64, 15, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.eof_)}},
    // uint32 chunk_size = 9;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileRequest, _impl_.chunk_size_), 16>(),
     {72, 16, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.chunk_size_)}},
    // bytes data = 10;
    {::_pbi::TcParser::FastBS1,
     {82, 5, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.data_)}},
    // bytes md5 = 11;
    {::_pbi::TcParser::FastBS1,
     {90, 6, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.md5_)}},
    // bytes iv = 12;
    {::_pbi::TcParser::FastBS1,
     {98, 7, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.iv_)}},
    // string path = 13;
    {::_pbi::TcParser::FastUS1,
     {106, 8, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.path_)}},
    // bytes chunk_md5 = 14;
    {::_pbi::TcParser::FastBS1,
     {114, 9, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.chunk_md5_)}},
    // uint64 upload_id = 15;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileRequest, _impl_.upload_id_), 17>(),
     {120, 17, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.upload_id_)}},
    // uint64 chunk_index = 16;
    {::_pbi::TcParser::FastV64S2,
     {384, 18, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.chunk_index_)}},
    // uint64 version = 17;
    {::_pbi::TcParser::FastV64S2,
     {392, 19, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.version_)}},
    // bytes block_hash = 18;
    {::_pbi::TcParser::FastBS2,
     {402, 10, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.block_hash_)}},
    // repeated bytes block_hashs = 19;
    {::_pbi::TcParser::FastBR2,
     {410, 0, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.block_hashs_)}},
    // repeated uint32 block_size = 20;
    {::_pbi::TcParser::FastV32P2,
     {418, 1, 0,
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.block_size_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // .CmdType type = 1;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.type_), _Internal::kHasBitsOffset + 11, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // string token = 2;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.token_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string clientID = 3;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.clientid_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 seckeyID = 4;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.seckeyid_), _Internal::kHasBitsOffset + 12, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // string filename = 5;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.filename_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint64 filesize = 6;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.filesize_), _Internal::kHasBitsOffset + 13, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 offset = 7;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.offset_), _Internal::kHasBitsOffset + 14, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // bool eof = 8;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.eof_), _Internal::kHasBitsOffset + 15, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // uint32 chunk_size = 9;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.chunk_size_), _Internal::kHasBitsOffset + 16, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // bytes data = 10;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.data_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes md5 = 11;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.md5_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // bytes iv = 12;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.iv_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // string path = 13;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.path_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // bytes chunk_md5 = 14;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.chunk_md5_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint64 upload_id = 15;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.upload_id_), _Internal::kHasBitsOffset + 17, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 chunk_index = 16;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.chunk_index_), _Internal::kHasBitsOffset + 18, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 version = 17;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.version_), _Internal::kHasBitsOffset + 19, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // bytes block_hash = 18;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.block_hash_), _Internal::kHasBitsOffset + 10, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // repeated bytes block_hashs = 19;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.block_hashs_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
    // repeated uint32 block_size = 20;
    {PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.block_size_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
  }},
  // no aux_entries
  {{
    "\13\0\5\10\0\10\0\0\0\0\0\0\0\4\0\0\0\0\0\0\0\0\0\0"
    "FileRequest"
    "token"
    "clientID"
    "filename"
    "path"
  }},
};
PROTOBUF_NOINLINE void FileRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:FileRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.block_hashs_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.block_size_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.token_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.clientid_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.filename_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _impl_.data_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _impl_.md5_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      _impl_.iv_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000700U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      _impl_.path_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      _impl_.chunk_md5_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      _impl_.block_hash_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000f800U)) {
    ::memset(&_impl_.type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.eof_) -
        reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.eof_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000f0000U)) {
    ::memset(&_impl_.chunk_size_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.version_) -
        reinterpret_cast<char*>(&_impl_.chunk_size_)) + sizeof(_impl_.version_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL FileRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const FileRequest& this_ = static_cast<const FileRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL FileRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const FileRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:FileRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .CmdType type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000800U)) {
    if (this_._internal_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_type(), target);
    }
  }

  // string token = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_token().empty()) {
      const ::std::string& _s = this_._internal_token();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FileRequest.token");
      target = stream->WriteStringMaybeAliased(2, _s, target);
    }
  }

  // string clientID = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    if (!this_._internal_clientid().empty()) {
      const ::std::string& _s = this_._internal_clientid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FileRequest.clientID");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // uint32 seckeyID = 4;
  if (CheckHasBit(cached_has_bits, 0x00001000U)) {
    if (this_._internal_seckeyid() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          4, this_._internal_seckeyid(), target);
    }
  }

  // string filename = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_filename().empty()) {
      const ::std::string& _s = this_._internal_filename();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FileRequest.filename");
      target = stream->WriteStringMaybeAliased(5, _s, target);
    }
  }

  // uint64 filesize = 6;
  if (CheckHasBit(cached_has_bits, 0x00002000U)) {
    if (this_._internal_filesize() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          6, this_._internal_filesize(), target);
    }
  }

  // uint64 offset = 7;
  if (CheckHasBit(cached_has_bits, 0x00004000U)) {
    if (this_._internal_offset() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          7, this_._internal_offset(), target);
    }
  }

  // bool eof = 8;
  if (CheckHasBit(cached_has_bits, 0x00008000U)) {
    if (this_._internal_eof() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          8, this_._internal_eof(), target);
    }
  }

  // uint32 chunk_size = 9;
  if (CheckHasBit(cached_has_bits, 0x00010000U)) {
    if (this_._internal_chunk_size() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          9, this_._internal_chunk_size(), target);
    }
  }

  // bytes data = 10;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (!this_._internal_data().empty()) {
      const ::std::string& _s = this_._internal_data();
      target = stream->WriteBytesMaybeAliased(10, _s, target);
    }
  }

  // bytes md5 = 11;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (!this_._internal_md5().empty()) {
      const ::std::string& _s = this_._internal_md5();
      target = stream->WriteBytesMaybeAliased(11, _s, target);
    }
  }

  // bytes iv = 12;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (!this_._internal_iv().empty()) {
      const ::std::string& _s = this_._internal_iv();
      target = stream->WriteBytesMaybeAliased(12, _s, target);
    }
  }

  // string path = 13;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (!this_._internal_path().empty()) {
      const ::std::string& _s = this_._internal_path();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FileRequest.path");
      target = stream->WriteStringMaybeAliased(13, _s, target);
    }
  }

  // bytes chunk_md5 = 14;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    if (!this_._internal_chunk_md5().empty()) {
      const ::std::string& _s = this_._internal_chunk_md5();
      target = stream->WriteBytesMaybeAliased(14, _s, target);
    }
  }

  // uint64 upload_id = 15;
  if (CheckHasBit(cached_has_bits, 0x00020000U)) {
    if (this_._internal_upload_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          15, this_._internal_upload_id(), target);
    }
  }

  // uint64 chunk_index = 16;
  if (CheckHasBit(cached_has_bits, 0x00040000U)) {
    if (this_._internal_chunk_index() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          16, this_._internal_chunk_index(), target);
    }
  }

  // uint64 version = 17;
  if (CheckHasBit(cached_has_bits, 0x00080000U)) {
    if (this_._internal_version() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          17, this_._internal_version(), target);
    }
  }

  // bytes block_hash = 18;
  if (CheckHasBit(cached_has_bits, 0x00000400U)) {
    if (!this_._internal_block_hash().empty()) {
      const ::std::string& _s = this_._internal_block_hash();
      target = stream->WriteBytesMaybeAliased(18, _s, target);
    }
  }

  // repeated bytes block_hashs = 19;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_block_hashs_size(); i < n; ++i) {
      const auto& s = this_._internal_block_hashs().Get(i);
      target = stream->WriteBytes(19, s, target);
    }
  }

  // repeated uint32 block_size = 20;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    {
      int byte_size = this_._impl_._block_size_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt32Packed(
            20, this_._internal_block_size(), byte_size, target);
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FileRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FileRequest::ByteSizeLong(const MessageLite& base) {
  const FileRequest& this_ = static_cast<const FileRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FileRequest::ByteSizeLong() const {
  const FileRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:FileRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // repeated bytes block_hashs = 19;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size +=
          2 * ::google::protobuf::internal::FromIntSize(this_._internal_block_hashs().size());
      for (int i = 0, n = this_._internal_block_hashs().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
            this_._internal_block_hashs().Get(i));
      }
    }
    // repeated uint32 block_size = 20;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_block_size(), 2,
              this_._impl_._block_size_cached_byte_size_);
    }
    // string token = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_token().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_token());
      }
    }
    // string clientID = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!this_._internal_clientid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_clientid());
      }
    }
    // string filename = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!this_._internal_filename().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_filename());
      }
    }
    // bytes data = 10;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (!this_._internal_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_data());
      }
    }
    // bytes md5 = 11;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (!this_._internal_md5().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_md5());
      }
    }
    // bytes iv = 12;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (!this_._internal_iv().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_iv());
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000ff00U)) {
    // string path = 13;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (!this_._internal_path().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_path());
      }
    }
    // bytes chunk_md5 = 14;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (!this_._internal_chunk_md5().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_chunk_md5());
      }
    }
    // bytes block_hash = 18;
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (!this_._internal_block_hash().empty()) {
        total_size += 2 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_block_hash());
      }
    }
    // .CmdType type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      if (this_._internal_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
      }
    }
    // uint32 seckeyID = 4;
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      if (this_._internal_seckeyid() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_seckeyid());
      }
    }
    // uint64 filesize = 6;
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      if (this_._internal_filesize() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_filesize());
      }
    }
    // uint64 offset = 7;
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      if (this_._internal_offset() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_offset());
      }
    }
    // bool eof = 8;
    if (CheckHasBit(cached_has_bits, 0x00008000U)) {
      if (this_._internal_eof() != 0) {
        total_size += 2;
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000f0000U)) {
    // uint32 chunk_size = 9;
    if (CheckHasBit(cached_has_bits, 0x00010000U)) {
      if (this_._internal_chunk_size() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_chunk_size());
      }
    }
    // uint64 upload_id = 15;
    if (CheckHasBit(cached_has_bits, 0x00020000U)) {
      if (this_._internal_upload_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_upload_id());
      }
    }
    // uint64 chunk_index = 16;
    if (CheckHasBit(cached_has_bits, 0x00040000U)) {
      if (this_._internal_chunk_index() != 0) {
        total_size += 2 + ::_pbi::WireFormatLite::UInt64Size(
                                        this_._internal_chunk_index());
      }
    }
    // uint64 version = 17;
    if (CheckHasBit(cached_has_bits, 0x00080000U)) {
      if (this_._internal_version() != 0) {
        total_size += 2 + ::_pbi::WireFormatLite::UInt64Size(
                                        this_._internal_version());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void FileRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<FileRequest*>(&to_msg);
  auto& from = static_cast<const FileRequest&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:FileRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_block_hashs()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_block_hashs());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_block_size()->MergeFrom(from._internal_block_size());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_token().empty()) {
        _this->_internal_set_token(from._internal_token());
      } else {
        if (_this->_impl_.token_.IsDefault()) {
          _this->_internal_set_token("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      if (!from._internal_clientid().empty()) {
        _this->_internal_set_clientid(from._internal_clientid());
      } else {
        if (_this->_impl_.clientid_.IsDefault()) {
          _this->_internal_set_clientid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!from._internal_filename().empty()) {
        _this->_internal_set_filename(from._internal_filename());
      } else {
        if (_this->_impl_.filename_.IsDefault()) {
          _this->_internal_set_filename("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (!from._internal_data().empty()) {
        _this->_internal_set_data(from._internal_data());
      } else {
        if (_this->_impl_.data_.IsDefault()) {
          _this->_internal_set_data("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (!from._internal_md5().empty()) {
        _this->_internal_set_md5(from._internal_md5());
      } else {
        if (_this->_impl_.md5_.IsDefault()) {
          _this->_internal_set_md5("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (!from._internal_iv().empty()) {
        _this->_internal_set_iv(from._internal_iv());
      } else {
        if (_this->_impl_.iv_.IsDefault()) {
          _this->_internal_set_iv("");
        }
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x0000ff00U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (!from._internal_path().empty()) {
        _this->_internal_set_path(from._internal_path());
      } else {
        if (_this->_impl_.path_.IsDefault()) {
          _this->_internal_set_path("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (!from._internal_chunk_md5().empty()) {
        _this->_internal_set_chunk_md5(from._internal_chunk_md5());
      } else {
        if (_this->_impl_.chunk_md5_.IsDefault()) {
          _this->_internal_set_chunk_md5("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (!from._internal_block_hash().empty()) {
        _this->_internal_set_block_hash(from._internal_block_hash());
      } else {
        if (_this->_impl_.block_hash_.IsDefault()) {
          _this->_internal_set_block_hash("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      if (from._internal_type() != 0) {
        _this->_impl_.type_ = from._impl_.type_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      if (from._internal_seckeyid() != 0) {
        _this->_impl_.seckeyid_ = from._impl_.seckeyid_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      if (from._internal_filesize() != 0) {
        _this->_impl_.filesize_ = from._impl_.filesize_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      if (from._internal_offset() != 0) {
        _this->_impl_.offset_ = from._impl_.offset_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00008000U)) {
      if (from._internal_eof() != 0) {
        _this->_impl_.eof_ = from._impl_.eof_;
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000f0000U)) {
    if (CheckHasBit(cached_has_bits, 0x00010000U)) {
      if (from._internal_chunk_size() != 0) {
        _this->_impl_.chunk_size_ = from._impl_.chunk_size_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00020000U)) {
      if (from._internal_upload_id() != 0) {
        _this->_impl_.upload_id_ = from._impl_.upload_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00040000U)) {
      if (from._internal_chunk_index() != 0) {
        _this->_impl_.chunk_index_ = from._impl_.chunk_index_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00080000U)) {
      if (from._internal_version() != 0) {
        _this->_impl_.version_ = from._impl_.version_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void FileRequest::CopyFrom(const FileRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:FileRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FileRequest::InternalSwap(FileRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.block_hashs_.InternalSwap(&other->_impl_.block_hashs_);
  _impl_.block_size_.InternalSwap(&other->_impl_.block_size_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.token_, &other->_impl_.token_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.clientid_, &other->_impl_.clientid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.filename_, &other->_impl_.filename_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.md5_, &other->_impl_.md5_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.iv_, &other->_impl_.iv_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.path_, &other->_impl_.path_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.chunk_md5_, &other->_impl_.chunk_md5_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.block_hash_, &other->_impl_.block_hash_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.version_)
      + sizeof(FileRequest::_impl_.version_)
      - PROTOBUF_FIELD_OFFSET(FileRequest, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::google::protobuf::Metadata FileRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class FileResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<FileResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(FileResponse, _impl_._has_bits_);
};

FileResponse::FileResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FileResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:FileResponse)
}
PROTOBUF_NDEBUG_INLINE FileResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::FileResponse& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        files_{visibility, arena, from.files_},
        finished_chunks_{visibility, arena, from.finished_chunks_},
        _finished_chunks_cached_byte_size_{0},
        missing_hashes_{visibility, arena, from.missing_hashes_},
        block_offsets_{visibility, arena, from.block_offsets_},
        _block_offsets_cached_byte_size_{0},
        message_(arena, from.message_),
        clientid_(arena, from.clientid_),
        data_(arena, from.data_),
        md5_(arena, from.md5_) {}

FileResponse::FileResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const FileResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, FileResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  FileResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, type_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, type_),
           offsetof(Impl_, chunk_size_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::chunk_size_));

  // @@protoc_insertion_point(copy_constructor:FileResponse)
}
PROTOBUF_NDEBUG_INLINE FileResponse::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        files_{visibility, arena},
        finished_chunks_{visibility, arena},
        _finished_chunks_cached_byte_size_{0},
        missing_hashes_{visibility, arena},
        block_offsets_{visibility, arena},
        _block_offsets_cached_byte_size_{0},
        message_(arena),
        clientid_(arena),
        data_(arena),
        md5_(arena) {}

inline void FileResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, type_),
           0,
           offsetof(Impl_, chunk_size_) -
               offsetof(Impl_, type_) +
               sizeof(Impl_::chunk_size_));
}
FileResponse::~FileResponse() {
  // @@protoc_insertion_point(destructor:FileResponse)
  SharedDtor(*this);
}
inline void FileResponse::SharedDtor(MessageLite& self) {
  FileResponse& this_ = static_cast<FileResponse&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.clientid_.Destroy();
  this_._impl_.data_.Destroy();
  this_._impl_.md5_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL FileResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) FileResponse(arena);
}
constexpr auto FileResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.files_) +
          decltype(FileResponse::_impl_.files_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.finished_chunks_) +
          decltype(FileResponse::_impl_.finished_chunks_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.missing_hashes_) +
          decltype(FileResponse::_impl_.missing_hashes_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.block_offsets_) +
          decltype(FileResponse::_impl_.block_offsets_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(FileResponse), alignof(FileResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&FileResponse::PlacementNew_,
                                 sizeof(FileResponse),
                                 alignof(FileResponse));
  }
}
constexpr auto FileResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_FileResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &FileResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<FileResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &FileResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<FileResponse>(), &FileResponse::ByteSizeLong,
              &FileResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(FileResponse, _impl_._cached_size_),
          false,
      },
      &FileResponse::kDescriptorMethods,
      &descriptor_table_File_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull FileResponse_class_data_ =
        FileResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
FileResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&FileResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(FileResponse_class_data_.tc_table);
  return FileResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 15, 1, 44, 2>
FileResponse::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(FileResponse, _impl_._has_bits_),
    0, // no _extensions_
    16, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294901824,  // skipmap
    offsetof(decltype(_table_), field_entries),
    15,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    FileResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::FileResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated uint64 block_offsets = 16;
    {::_pbi::TcParser::FastV64P2,
     {386, 3, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.block_offsets_)}},
    // .CmdType type = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileResponse, _impl_.type_), 8>(),
     {8, 8, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.type_)}},
    // bool status = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FileResponse, _impl_.status_), 9>(),
     {16, 9, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.status_)}},
    // string message = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 4, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.message_)}},
    // string clientID = 4;
    {::_pbi::TcParser::FastUS1,
     {34, 5, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.clientid_)}},
    // uint64 offset = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileResponse, _impl_.offset_), 11>(),
     {40, 11, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.offset_)}},
    // bool eof = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(FileResponse, _impl_.eof_), 10>(),
     {48, 10, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.eof_)}},
    {::_pbi::TcParser::MiniParse, {}},
    // bytes data = 8;
    {::_pbi::TcParser::FastBS1,
     {66, 6, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.data_)}},
    // repeated .FileItem files = 9;
    {::_pbi::TcParser::FastMtR1,
     {74, 0, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.files_)}},
    // uint32 chunk_size = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(FileResponse, _impl_.chunk_size_), 14>(),
     {80, 14, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.chunk_size_)}},
    // bytes md5 = 11;
    {::_pbi::TcParser::FastBS1,
     {90, 7, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.md5_)}},
    // uint64 filesize = 12;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileResponse, _impl_.filesize_), 12>(),
     {96, 12, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.filesize_)}},
    // uint64 upload_id = 13;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(FileResponse, _impl_.upload_id_), 13>(),
     {104, 13, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.upload_id_)}},
    // repeated uint32 finished_chunks = 14;
    {::_pbi::TcParser::FastV32P1,
     {114, 1, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.finished_chunks_)}},
    // repeated bytes missing_hashes = 15;
    {::_pbi::TcParser::FastBR1,
     {122, 2, 0,
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.missing_hashes_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .CmdType type = 1;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.type_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
    // bool status = 2;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.status_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // string message = 3;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.message_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string clientID = 4;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.clientid_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint64 offset = 5;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.offset_), _Internal::kHasBitsOffset + 11, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // bool eof = 6;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.eof_), _Internal::kHasBitsOffset + 10, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // bytes data = 8;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.data_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // repeated .FileItem files = 9;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.files_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint32 chunk_size = 10;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.chunk_size_), _Internal::kHasBitsOffset + 14, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
    // bytes md5 = 11;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.md5_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // uint64 filesize = 12;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.filesize_), _Internal::kHasBitsOffset + 12, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // uint64 upload_id = 13;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.upload_id_), _Internal::kHasBitsOffset + 13, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // repeated uint32 finished_chunks = 14;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.finished_chunks_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt32)},
    // repeated bytes missing_hashes = 15;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.missing_hashes_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcRepeated | ::_fl::kBytes | ::_fl::kRepSString)},
    // repeated uint64 block_offsets = 16;
    {PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.block_offsets_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcRepeated | ::_fl::kPackedUInt64)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::FileItem>()},
  }},
  {{
    "\14\0\0\7\10\0\0\0\0\0\0\0\0\0\0\0"
    "FileResponse"
    "message"
    "clientID"
  }},
};
PROTOBUF_NOINLINE void FileResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:FileResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _impl_.files_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _impl_.finished_chunks_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _impl_.missing_hashes_.Clear();
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000008U)) {
      _impl_.block_offsets_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.message_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _impl_.clientid_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _impl_.data_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      _impl_.md5_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00007f00U)) {
    ::memset(&_impl_.type_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.chunk_size_) -
        reinterpret_cast<char*>(&_impl_.type_)) + sizeof(_impl_.chunk_size_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL FileResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const FileResponse& this_ = static_cast<const FileResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL FileResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const FileResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:FileResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // .CmdType type = 1;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    if (this_._internal_type() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          1, this_._internal_type(), target);
    }
  }

  // bool status = 2;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    if (this_._internal_status() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          2, this_._internal_status(), target);
    }
  }

  // string message = 3;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_message().empty()) {
      const ::std::string& _s = this_._internal_message();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FileResponse.message");
      target = stream->WriteStringMaybeAliased(3, _s, target);
    }
  }

  // string clientID = 4;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (!this_._internal_clientid().empty()) {
      const ::std::string& _s = this_._internal_clientid();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "FileResponse.clientID");
      target = stream->WriteStringMaybeAliased(4, _s, target);
    }
  }

  // uint64 offset = 5;
  if (CheckHasBit(cached_has_bits, 0x00000800U)) {
    if (this_._internal_offset() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          5, this_._internal_offset(), target);
    }
  }

  // bool eof = 6;
  if (CheckHasBit(cached_has_bits, 0x00000400U)) {
    if (this_._internal_eof() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteBoolToArray(
          6, this_._internal_eof(), target);
    }
  }

  // bytes data = 8;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (!this_._internal_data().empty()) {
      const ::std::string& _s = this_._internal_data();
      target = stream->WriteBytesMaybeAliased(8, _s, target);
    }
  }

  // repeated .FileItem files = 9;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_files_size());
         i < n; i++) {
      const auto& repfield = this_._internal_files().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              9, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // uint32 chunk_size = 10;
  if (CheckHasBit(cached_has_bits, 0x00004000U)) {
    if (this_._internal_chunk_size() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
          10, this_._internal_chunk_size(), target);
    }
  }

  // bytes md5 = 11;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    if (!this_._internal_md5().empty()) {
      const ::std::string& _s = this_._internal_md5();
      target = stream->WriteBytesMaybeAliased(11, _s, target);
    }
  }

  // uint64 filesize = 12;
  if (CheckHasBit(cached_has_bits, 0x00001000U)) {
    if (this_._internal_filesize() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          12, this_._internal_filesize(), target);
    }
  }

  // uint64 upload_id = 13;
  if (CheckHasBit(cached_has_bits, 0x00002000U)) {
    if (this_._internal_upload_id() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
          13, this_._internal_upload_id(), target);
    }
  }

  // repeated uint32 finished_chunks = 14;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
    {
      int byte_size = this_._impl_._finished_chunks_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt32Packed(
            14, this_._internal_finished_chunks(), byte_size, target);
      }
    }
  }

  // repeated bytes missing_hashes = 15;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
    for (int i = 0, n = this_._internal_missing_hashes_size(); i < n; ++i) {
      const auto& s = this_._internal_missing_hashes().Get(i);
      target = stream->WriteBytes(15, s, target);
    }
  }

  // repeated uint64 block_offsets = 16;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000008U)) {
    {
      int byte_size = this_._impl_._block_offsets_cached_byte_size_.Get();
      if (byte_size > 0) {
        target = stream->WriteUInt64Packed(
            16, this_._internal_block_offsets(), byte_size, target);
      }
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:FileResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t FileResponse::ByteSizeLong(const MessageLite& base) {
  const FileResponse& this_ = static_cast<const FileResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t FileResponse::ByteSizeLong() const {
  const FileResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:FileResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // repeated .FileItem files = 9;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_files_size();
      for (const auto& msg : this_._internal_files()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated uint32 finished_chunks = 14;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt32SizeWithPackedTagSize(
              this_._internal_finished_chunks(), 1,
              this_._impl_._finished_chunks_cached_byte_size_);
    }
    // repeated bytes missing_hashes = 15;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_missing_hashes().size());
      for (int i = 0, n = this_._internal_missing_hashes().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::BytesSize(
            this_._internal_missing_hashes().Get(i));
      }
    }
    // repeated uint64 block_offsets = 16;
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000008U)) {
      total_size +=
          ::_pbi::WireFormatLite::UInt64SizeWithPackedTagSize(
              this_._internal_block_offsets(), 2,
              this_._impl_._block_offsets_cached_byte_size_);
    }
    // string message = 3;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!this_._internal_message().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_message());
      }
    }
    // string clientID = 4;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (!this_._internal_clientid().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_clientid());
      }
    }
    // bytes data = 8;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (!this_._internal_data().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_data());
      }
    }
    // bytes md5 = 11;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (!this_._internal_md5().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::BytesSize(
                                        this_._internal_md5());
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00007f00U)) {
    // .CmdType type = 1;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (this_._internal_type() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_type());
      }
    }
    // bool status = 2;
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (this_._internal_status() != 0) {
        total_size += 2;
      }
    }
    // bool eof = 6;
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (this_._internal_eof() != 0) {
        total_size += 2;
      }
    }
    // uint64 offset = 5;
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      if (this_._internal_offset() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_offset());
      }
    }
    // uint64 filesize = 12;
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      if (this_._internal_filesize() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_filesize());
      }
    }
    // uint64 upload_id = 13;
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      if (this_._internal_upload_id() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
            this_._internal_upload_id());
      }
    }
    // uint32 chunk_size = 10;
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      if (this_._internal_chunk_size() != 0) {
        total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
            this_._internal_chunk_size());
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void FileResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<FileResponse*>(&to_msg);
  auto& from = static_cast<const FileResponse&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:FileResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_files()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_files());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_finished_chunks()->MergeFrom(from._internal_finished_chunks());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000004U)) {
      _this->_internal_mutable_missing_hashes()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_missing_hashes());
    }
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000008U)) {
      _this->_internal_mutable_block_offsets()->MergeFrom(from._internal_block_offsets());
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (!from._internal_message().empty()) {
        _this->_internal_set_message(from._internal_message());
      } else {
        if (_this->_impl_.message_.IsDefault()) {
          _this->_internal_set_message("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      if (!from._internal_clientid().empty()) {
        _this->_internal_set_clientid(from._internal_clientid());
      } else {
        if (_this->_impl_.clientid_.IsDefault()) {
          _this->_internal_set_clientid("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      if (!from._internal_data().empty()) {
        _this->_internal_set_data(from._internal_data());
      } else {
        if (_this->_impl_.data_.IsDefault()) {
          _this->_internal_set_data("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      if (!from._internal_md5().empty()) {
        _this->_internal_set_md5(from._internal_md5());
      } else {
        if (_this->_impl_.md5_.IsDefault()) {
          _this->_internal_set_md5("");
        }
      }
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00007f00U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      if (from._internal_type() != 0) {
        _this->_impl_.type_ = from._impl_.type_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      if (from._internal_status() != 0) {
        _this->_impl_.status_ = from._impl_.status_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000400U)) {
      if (from._internal_eof() != 0) {
        _this->_impl_.eof_ = from._impl_.eof_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000800U)) {
      if (from._internal_offset() != 0) {
        _this->_impl_.offset_ = from._impl_.offset_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00001000U)) {
      if (from._internal_filesize() != 0) {
        _this->_impl_.filesize_ = from._impl_.filesize_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00002000U)) {
      if (from._internal_upload_id() != 0) {
        _this->_impl_.upload_id_ = from._impl_.upload_id_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00004000U)) {
      if (from._internal_chunk_size() != 0) {
        _this->_impl_.chunk_size_ = from._impl_.chunk_size_;
      }
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void FileResponse::CopyFrom(const FileResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:FileResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void FileResponse::InternalSwap(FileResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.files_.InternalSwap(&other->_impl_.files_);
  _impl_.finished_chunks_.InternalSwap(&other->_impl_.finished_chunks_);
  _impl_.missing_hashes_.InternalSwap(&other->_impl_.missing_hashes_);
  _impl_.block_offsets_.InternalSwap(&other->_impl_.block_offsets_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.clientid_, &other->_impl_.clientid_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.data_, &other->_impl_.data_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.md5_, &other->_impl_.md5_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.chunk_size_)
      + sizeof(FileResponse::_impl_.chunk_size_)
      - PROTOBUF_FIELD_OFFSET(FileResponse, _impl_.type_)>(
          reinterpret_cast<char*>(&_impl_.type_),
          reinterpret_cast<char*>(&other->_impl_.type_));
}

::google::protobuf::Metadata FileResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_File_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
